### ISSUE TITLE
支持半路捕获回放

### ISSUE THREAD

**Issue by wangbin579** [session-replay-tools/mysql-sgt-replay-module#1]
由于部分场合是长连接场合，运行tcpcopy的时候，session已经存在，需要补全登入验证过程才能支持回放。

通过构造一个有验证过程的session或者利用离线数据，获取登入验证数据包，从而达到补全session的目的

**Comment by longxibendi** [comment]
最近做压测，测试MySQL已经设置skip-grant了，用这个能支持复制流量，离线回放吗，我看configure的时候 ./configure --enable-offline --set-protocol-module=mysql-sgt-replay-module
--enable-offline没有这个配置项。所以关于 离线流量回放，能不能写个详细的步骤。谢谢。

**Comment by wangbin579** [comment]
1.0版本，离线回放是--offline，不是--enable-offline了。
看configure help即可
对于offline回放，pcap文件中完整的session才能回放
方法其实很简单，除了configure不同以外，运行只需要多加上-i参数，用来指定pcap文件路径，其它过程一样

**Comment by wangbin579** [comment]
离线目前还不具备半路回放，实时模式下，经过测试，是支持的，条件如下：
1）测试服务器的MySQL工作在skip-grant-tables方式下
2）利用mysql命令行，访问线上服务器MySQL，目的是让tcpcopy捕获登入数据包，从而激活整个SQL请求复制

**Comment by longxibendi** [comment]
问题已解决，感谢王斌。
