### ISSUE TITLE
test-server上回放不了mysql流量

### ISSUE THREAD

**Issue by wangjuan08** [session-replay-tools/mysql-sgt-replay-module#3]
tcpcopy客户端日志如下：
2017/01/16 23:38:17 +554 [debug] fir auth packet is null
2017/01/16 23:38:17 +556 [debug] fir auth packet is null
2017/01/16 23:38:17 +664 [debug] fir auth packet is null
2017/01/16 23:38:17 +666 [debug] fir auth packet is null
2017/01/16 23:38:17 +775 [debug] fir auth packet is null
2017/01/16 23:38:17 +778 [debug] fir auth packet is null
2017/01/16 23:38:17 +884 [debug] fir auth packet is null
2017/01/16 23:38:17 +885 [debug] fir auth packet is null

配置：
1. tcpcopy：192.168.177.84 安装数据库mysql, ./configure --set-protocol-module=mysql-sgt-replay-module --with-debug   配置了plugin.conf和plugin.conf.default 
2. intecept:192.168.177.85 ./configure
3 .测试机器：192.168.177.88  安装mysql数据库 ，route add -host 192.168.177.87 gw 192.168.177.85 
Start MySQL with --skip-grant-tables
其中 192.168.177.87 为调用192.168.177.84数据库的客户端机器

但是不知道为什么一直提示fir auth packet is null，有什么解决办法吗？

**Comment by wangbin579** [comment]
你可以尝试用命令行登入84机器的线上mysql，这样就会被tcpcopy捕获到第一次认证数据包（first auth），这样就应该不会报了，如果还报，请给我发送tcpcopy的log文件，我分析一下。

btw，由于mysql回放，需要有第一次认证信息（哪怕是skip方式），如果没有捕获，就会报上面的提示。
